//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int sId { get; set; }
        public int uId { get; set; }
        public int mId { get; set; }
    
        public virtual Müşteri Müşteri { get; set; }
        public virtual Ürünler Ürünler { get; set; }
    }
}
