//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yönetici
    {
        public int yId { get; set; }
        public int kId { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string yas { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
